## Practice Transposed CNN

without training process

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/miokobayashii/summerschool2022/blob/main/day02/practiceTCNN.ipynb)

In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

from keras.layers import Dense, Flatten, Reshape, Input
from keras.models import Sequential
from keras.layers.convolutional import Conv2D, Conv2DTranspose

In [2]:
def my_filter(shape, dtype=None):

    f = np.array([
            [[[0]], [[-1]], [[0]]],
            [[[-1]], [[4]], [[-1]]],
            [[[0]], [[-1]], [[0]]]
        ])
    return f

In [3]:
input_mat = np.array([
    [ [1], [2] ],
    [ [3], [4] ],
])

print(input_mat.shape)
# we need to give the batch size. 
# here we will just add a dimension at the beginning which makes batch size=1
input_mat = input_mat.reshape((1, 2, 2, 1))

(2, 2, 1)


In [10]:
model = Sequential()
model.add(Input(shape=(2,2,1)))                           

cnn_1 = Conv2DTranspose(1, kernel_size=3, strides=2, kernel_initializer=my_filter, padding='valid')
model.add(cnn_1)
model.build()

In [11]:
out = model.predict(input_mat)
print(out.reshape((out.shape[1],out.shape[2])))

[[ 0. -1.  0. -2.  0.]
 [-1.  4. -3.  8. -2.]
 [ 0. -4.  0. -6.  0.]
 [-3. 12. -7. 16. -4.]
 [ 0. -3.  0. -4.  0.]]


### Answers

(1): Laplacian filter 

(1)-1: Stride = 1, Mode=‘same’

(1)-2: Stride = 1, Mode=‘valid’

(1)-3: Stride = 2, Mode=‘valid’

(2): Prewitt filter

(2)-1: Stride = 1, Mode=‘same’

(2)-2: Stride = 1, Mode=‘valid’

(2)-3: Stride = 2, Mode=‘valid’

(3): Prewitt filter 

(3)-1: Stride = 1, Mode=‘same’

(3)-2: Stride = 1, Mode=‘valid’

(3)-3: Stride = 2, Mode=‘valid’