## Practice Transposed CNN

without training process

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/miokobayashii/summerschool2022/blob/main/day03/Practice10_practiceTCNN.ipynb)

### Practice10_1 Please Confirm the values of an output with Python program 

strides = 1
output_padding = 0

<img src="https://drive.google.com/uc?id=186HADebL4TL47hynLwSMYp3j4YjxavT5" witdh="700">

In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

from keras.layers import Dense, Flatten, Reshape, Input
from keras.models import Sequential
from keras.layers.convolutional import Conv2D, Conv2DTranspose

In [8]:
def my_filter(shape, dtype=None):

    f = np.array([
            [[[0]], [[-1]], [[0]]],
            [[[-1]], [[5]], [[-1]]],
            [[[0]], [[-1]], [[0]]]
        ])
    return f

In [9]:
input_mat = np.array([
    [ [1], [1] ],
    [ [1], [1] ],
])

print(input_mat.shape)
# we need to give the batch size. 
# here we will just add a dimension at the beginning which makes batch size=1
input_mat = input_mat.reshape((1, 2, 2, 1))

(2, 2, 1)


In [12]:
model = Sequential()
model.add(Input(shape=(2,2,1)))                           

cnn_1 = Conv2DTranspose(1, kernel_size=3, strides=1, kernel_initializer=my_filter, padding='valid', output_padding=0)
model.add(cnn_1)
model.build()

In [13]:
out = model.predict(input_mat)
print(out.reshape((out.shape[1],out.shape[2])))

[[ 0. -1. -1.  0.]
 [-1.  3.  3. -1.]
 [-1.  3.  3. -1.]
 [ 0. -1. -1.  0.]]




---
**Your answer:**


(sample)
```
cnn_1 = Conv2DTranspose(1, kernel_size=3, strides=1, kernel_initializer=my_filter, padding='valid', output_padding=0)
```



```
[[ 0. -1. -1.  0.]
 [-1.  3.  3. -1.]
 [-1.  3.  3. -1.]
 [ 0. -1. -1.  0.]]

```








---
### Practice10_2 Please Confirm the values of an output with Python program 

<img src="https://drive.google.com/uc?id=10qmG-fRgzMIDIMniIkC1_80OV9xbGoMp" witdh="700">

---
**Your answer:**



 

---
### Practice10_3 Laplacian filter and Prewitt filter
<img src="https://drive.google.com/uc?id=1B9Bk-sW81e19QzdRpawGXpEKBzZaGyK2" width="150">
<img src="https://drive.google.com/uc?id=1b31q7MHzCX7l1NpC5SvEoLoSzuHXHfRV" width="600">



---
**Your answer:**

(1): Laplacian filter 

(1)-1: Stride = 1, Mode=‘same’

(1)-2: Stride = 1, Mode=‘valid’

(1)-3: Stride = 2, Mode=‘valid’

(2): Prewitt filter

(2)-1: Stride = 1, Mode=‘same’

(2)-2: Stride = 1, Mode=‘valid’

(2)-3: Stride = 2, Mode=‘valid’

(3): Prewitt filter 

(3)-1: Stride = 1, Mode=‘same’

(3)-2: Stride = 1, Mode=‘valid’

(3)-3: Stride = 2, Mode=‘valid’