## Practice CNN

without training process

In [22]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

from keras.layers import Dense, Flatten, Reshape, Input
from keras.models import Sequential
from keras.layers.convolutional import Conv2D, Conv2DTranspose

In [23]:
def my_filter(shape, dtype=None):

    f = np.array([
            [[[0]], [[0]], [[0]]],
            [[[0]], [[0]], [[0]]],
            [[[0]], [[0]], [[0]]]
        ])
    return f

In [24]:
input_mat = np.array([
    [ [1], [2], [3], [4] ],
    [ [5], [6], [7], [8] ],
    [ [9], [10], [11], [12] ],
    [ [13], [14], [15], [16] ]
])

print(input_mat.shape)
# we need to give the batch size. 
# here we will just add a dimension at the beginning which makes batch size=1
input_mat = input_mat.reshape((1, 4, 4, 1))

(4, 4, 1)


In [25]:
model = Sequential()
model.add(Input(shape=(4,4,1)))                           

cnn_1 = Conv2D(1, kernel_size=3, strides=1, kernel_initializer=my_filter, padding='same')
model.add(cnn_1)
model.build()

In [26]:
out = model.predict(input_mat)

print(out.reshape((out.shape[1],out.shape[2])))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
