## Practice Transposed CNN   3 input layers

without training process

In [42]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

from keras.layers import Dense, Flatten, Reshape, Input
from keras.models import Sequential
from keras.layers.convolutional import Conv2D, Conv2DTranspose

In [43]:
def my_filter3(shape, dtype=None):

    f = np.array([
            [[[0,0,0]], [[-1,-1,-1]], [[0,0,0]]],
            [[[-1,-1,-1]], [[5,5,5]], [[-1,-1,-1]]],
            [[[0,0,0]], [[-1,-1,-1]], [[0,0,0]]]
        ])
    return f

In [44]:
#[
#    [ 0, 1 ],
#    [ 0, -1 ],
#],[
#    [ 0, 1 ],
#    [ 1, 0 ],
#],[
#    [ 1, 1 ],
#    [ 1, 1 ],
#]
input_mat = np.array([
    [ [0, 0, 1], [1,1,1] ],
    [ [0, 1, 1], [-1,0,1] ],
])


print(input_mat)
# we need to give the batch size. 
# here we will just add a dimension at the beginning which makes batch size=1
input_mat = input_mat.reshape((1, 2, 2, 3))
print (input_mat.shape)
input_mat

[[[ 0  0  1]
  [ 1  1  1]]

 [[ 0  1  1]
  [-1  0  1]]]
(1, 2, 2, 3)


array([[[[ 0,  0,  1],
         [ 1,  1,  1]],

        [[ 0,  1,  1],
         [-1,  0,  1]]]])

In [45]:
model = Sequential()
model.add(Input(shape=(2,2,3)))

cnn_1 = Conv2DTranspose(1, kernel_size=3, strides=2, kernel_initializer=my_filter3, padding='same')
model.add(cnn_1)
model.build()

In [46]:
out = model.predict(input_mat)
print(out.reshape((out.shape[1],out.shape[2])))

[[ 0. -1.  0. -3.]
 [-1.  5. -4. 15.]
 [ 0. -3.  0. -3.]
 [-2. 10. -2.  0.]]


### Confirmation

In [48]:
def my_filter(shape, dtype=None):

    f = np.array([
            [[[0]], [[-1]], [[0]]],
            [[[-1]], [[5]], [[-1]]],
            [[[0]], [[-1]], [[0]]]
        ])
    return f

In [49]:
model = Sequential()
model.add(Input(shape=(2,2,1)))                           

cnn_2 = Conv2DTranspose(1, kernel_size=3, strides=2, kernel_initializer=my_filter, padding='same')
model.add(cnn_2)
model.build()

### Layer 1

In [58]:
input_mat = np.array([
    [ [0], [1] ],
    [ [0], [-1] ],
])

# we need to give the batch size. 
# here we will just add a dimension at the beginning which makes batch size=1
input_mat = input_mat.reshape((1, 2, 2, 1))
out = model.predict(input_mat)
layer1 = np.array(out)
print(out.reshape((out.shape[1],out.shape[2])))

[[ 0.  0.  0. -1.]
 [ 0.  0. -1.  5.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  1. -5.]]


### Layer 2

In [59]:
input_mat = np.array([
    [ [0], [1] ],
    [ [1], [0] ],
])

# we need to give the batch size. 
# here we will just add a dimension at the beginning which makes batch size=1
input_mat = input_mat.reshape((1, 2, 2, 1))
out = model.predict(input_mat)
layer2 = np.array(out)
print(out.reshape((out.shape[1],out.shape[2])))


[[ 0.  0.  0. -1.]
 [ 0.  0. -1.  5.]
 [ 0. -1.  0. -1.]
 [-1.  5. -1.  0.]]


### Layer3

In [60]:
input_mat = np.array([
    [ [1], [1] ],
    [ [1], [1] ],
])

# we need to give the batch size. 
# here we will just add a dimension at the beginning which makes batch size=1
input_mat = input_mat.reshape((1, 2, 2, 1))
out = model.predict(input_mat)
layer3 = np.array(out)
print(out.reshape((out.shape[1],out.shape[2])))

[[ 0. -1.  0. -1.]
 [-1.  5. -2.  5.]
 [ 0. -2.  0. -2.]
 [-1.  5. -2.  5.]]


In [61]:
print((layer1+layer2+layer3).reshape(4,4))

[[ 0. -1.  0. -3.]
 [-1.  5. -4. 15.]
 [ 0. -3.  0. -3.]
 [-2. 10. -2.  0.]]
