## Practice CNN

without training process

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/miokobayashii/summerschool2022/blob/main/day01/practiceCNN_filters.ipynb)

In [ ]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

from keras.layers import Dense, Flatten, Reshape, Input
from keras.models import Sequential
from keras.layers.convolutional import Conv2D, Conv2DTranspose

In [ ]:
def my_filter(shape, dtype=None):

    f = np.array([
            [[[0]], [[0]], [[0]]],
            [[[0]], [[0]], [[0]]],
            [[[0]], [[0]], [[0]]]
        ])
    return f

In [ ]:
input_mat = np.array([
    [ [1], [2], [3], [4] ],
    [ [5], [6], [7], [8] ],
    [ [9], [10], [11], [12] ],
    [ [13], [14], [15], [16] ]
])

print(input_mat.shape)
# we need to give the batch size. 
# here we will just add a dimension at the beginning which makes batch size=1
input_mat = input_mat.reshape((1, 4, 4, 1))

(4, 4, 1)


In [ ]:
model = Sequential()
model.add(Input(shape=(4,4,1)))                           

cnn_1 = Conv2D(1, kernel_size=3, strides=1, kernel_initializer=my_filter, padding='same')
model.add(cnn_1)
model.build()

In [ ]:
out = model.predict(input_mat)

print(out.reshape((out.shape[1],out.shape[2])))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


## Practice filters

## (1) Laplacian filter

### (1)-1: Stride = 1, Mode = 'same'

### (1)-2: Stride = 1, Mode = 'valid'

## (2) Prewitt filter I

### (2)-1: Stride = 1, Mode = 'same'

### (2)-2: Stride = 1, Mode = 'valid'

## (3) Prewitt filter II

### (3)-1: Stride = 1, Mode = 'same'

### (3)-1: Stride = 1, Mode = 'valid'