## Practice Transposed CNN

without training process

In [1]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np

from keras.layers import Dense, Flatten, Reshape, Input
from keras.models import Sequential
from keras.layers.convolutional import Conv2D, Conv2DTranspose

In [2]:
def my_filter(shape, dtype=None):

    f = np.array([
            [[[0]], [[-1]], [[0]]],
            [[[-1]], [[5]], [[-1]]],
            [[[0]], [[-1]], [[0]]]
        ])
    return f

In [3]:
input_mat = np.array([
    [ [1], [1] ],
    [ [1], [1] ],
])

print(input_mat.shape)
# we need to give the batch size. 
# here we will just add a dimension at the beginning which makes batch size=1
input_mat = input_mat.reshape((1, 2, 2, 1))

(2, 2, 1)


In [8]:
model = Sequential()
model.add(Input(shape=(2,2,1)))                           

cnn_1 = Conv2DTranspose(1, kernel_size=3, strides=1, kernel_initializer=my_filter, padding='valid')
model.add(cnn_1)
model.build()

In [9]:
out = model.predict(input_mat)
print(out.reshape((out.shape[1],out.shape[2])))

[[ 0. -1. -1.  0.]
 [-1.  3.  3. -1.]
 [-1.  3.  3. -1.]
 [ 0. -1. -1.  0.]]
